package com.uanl.ss2020.CursoJavaWeb.model;
// default package
// Generated 26/06/2020 08:50:58 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonView;
import com.uanl.ss2020.CursoJavaWeb.model.Usuario.UsuarioDatosGenerales;
import com.uanl.ss2020.CursoJavaWeb.model.Usuario.UsuarioDatosGrid;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "sql9350583", uniqueConstraints = @UniqueConstraint(columnNames = "matricula"))
public class Alumno implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@JsonView(UsuarioDatosGrid.class) private Integer idAlumno;
	@JsonView(UsuarioDatosGrid.class) private int matricula;

	public Alumno() {
	}

	public Alumno(int matricula) {
		this.matricula = matricula;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAlumno", unique = true, nullable = false)
	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		this.idAlumno = idAlumno;
	}

	@Column(name = "matricula", unique = true, nullable = false)
	public int getMatricula() {
		return this.matricula;
	}

	public void setMatricula(int matricula) {
		this.matricula = matricula;
	}

}
