package com.uanl.ss2020.CursoJavaWeb.model;
// default package
// Generated 26/06/2020 08:50:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonView;
import com.uanl.ss2020.CursoJavaWeb.model.Usuario.UsuarioDatosGenerales;

/**
 * Estatus generated by hbm2java
 */
@Entity
@Table(name = "estatus", catalog = "sql9350583", uniqueConstraints = @UniqueConstraint(columnNames = "clave"))
public class Estatus implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@JsonView(UsuarioDatosGenerales.class) private Integer idEstatus;
	@JsonView(UsuarioDatosGenerales.class) private String nombre;
	@JsonView(UsuarioDatosGenerales.class) private String clave;
	
	private Set<Materia> materias = new HashSet<Materia>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Estatus() {
	}
	
	public Estatus(int idEstatus) {
		this.idEstatus = idEstatus;
	}

	public Estatus(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public Estatus(String nombre, String clave, Set<Materia> materias, Set<Usuario> usuarios) {
		this.nombre = nombre;
		this.clave = clave;
		this.materias = materias;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEstatus", unique = true, nullable = false)
	public Integer getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(Integer idEstatus) {
		this.idEstatus = idEstatus;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", unique = true, nullable = false, length = 1)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatus")
	public Set<Materia> getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set<Materia> materias) {
		this.materias = materias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatus")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
