package com.uanl.ss2020.CursoJavaWeb.model;
// default package
// Generated 26/06/2020 08:50:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name = "materia", catalog = "sql9350583", uniqueConstraints = @UniqueConstraint(columnNames = "clave"))
public class Materia implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idMateria;
	private Estatus estatus;
	private String nombre;
	private String clave;
	private Set<Grupo> grupos = new HashSet<Grupo>(0);

	public Materia() {
	}

	public Materia(Estatus estatus, String nombre, String clave) {
		this.estatus = estatus;
		this.nombre = nombre;
		this.clave = clave;
	}

	public Materia(Estatus estatus, String nombre, String clave, Set<Grupo> grupos) {
		this.estatus = estatus;
		this.nombre = nombre;
		this.clave = clave;
		this.grupos = grupos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMateria", unique = true, nullable = false)
	public Integer getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(Integer idMateria) {
		this.idMateria = idMateria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstatus", nullable = false)
	public Estatus getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Estatus estatus) {
		this.estatus = estatus;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", unique = true, nullable = false, length = 45)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materia")
	public Set<Grupo> getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Set<Grupo> grupos) {
		this.grupos = grupos;
	}

}
