package com.uanl.ss2020.CursoJavaWeb.model;
// default package
// Generated 26/06/2020 08:50:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;
import com.uanl.ss2020.CursoJavaWeb.model.Usuario.UsuarioDatosGenerales;

/**
 * TipoPerfil generated by hbm2java
 */
@Entity
@Table(name = "tipoPerfil", catalog = "sql9350583")
public class TipoPerfil implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idTipoPerfil;
	
	@JsonView(UsuarioDatosGenerales.class) private String nombre;
	@JsonView(UsuarioDatosGenerales.class) private String clave;
	
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public TipoPerfil() {
	}
	
	public TipoPerfil(int idTipoPerfil) {
		this.idTipoPerfil = idTipoPerfil;
	}

	public TipoPerfil(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public TipoPerfil(String nombre, String clave, Set<Usuario> usuarios) {
		this.nombre = nombre;
		this.clave = clave;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTipoPerfil", unique = true, nullable = false)
	public Integer getIdTipoPerfil() {
		return this.idTipoPerfil;
	}

	public void setIdTipoPerfil(Integer idTipoPerfil) {
		this.idTipoPerfil = idTipoPerfil;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", nullable = false, length = 3)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPerfil")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
