package com.uanl.ss2020.CursoJavaWeb.model;
// default package
// Generated 26/06/2020 08:50:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "sql9350583")
public class Usuario implements java.io.Serializable {

	public interface UsuarioDatosGenerales {}
	public interface UsuarioDatosGrid extends UsuarioDatosGenerales {}
	
	private static final long serialVersionUID = 1L;
	@JsonView(UsuarioDatosGenerales.class) private int idUsuario;
	
	@JsonView(UsuarioDatosGrid.class) private Alumno alumno;
	@JsonView(UsuarioDatosGrid.class) private Estatus estatus;
	@JsonView(UsuarioDatosGrid.class) private Maestro maestro;
	
	@JsonView(UsuarioDatosGenerales.class) private TipoPerfil tipoPerfil;
	@JsonView(UsuarioDatosGenerales.class) private String nombre;
	@JsonView(UsuarioDatosGenerales.class) private String usuario;
	
	private String contrasena;
	private Set<Curso> cursos = new HashSet<Curso>(0);

	public Usuario() {
	}

	public Usuario(int idUsuario, Estatus estatus, TipoPerfil tipoPerfil, String nombre, String usuario,
			String contrasena) {
		this.idUsuario = idUsuario;
		this.estatus = estatus;
		this.tipoPerfil = tipoPerfil;
		this.nombre = nombre;
		this.usuario = usuario;
		this.contrasena = contrasena;
	}

	public Usuario(int idUsuario, Alumno alumno, Estatus estatus, Maestro maestro, TipoPerfil tipoPerfil, String nombre,
			String usuario, String contrasena, Set<Curso> cursos) {
		this.idUsuario = idUsuario;
		this.alumno = alumno;
		this.estatus = estatus;
		this.maestro = maestro;
		this.tipoPerfil = tipoPerfil;
		this.nombre = nombre;
		this.usuario = usuario;
		this.contrasena = contrasena;
		this.cursos = cursos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idUsuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAlumno")
	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstatus", nullable = false)
	public Estatus getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Estatus estatus) {
		this.estatus = estatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMaestro")
	public Maestro getMaestro() {
		return this.maestro;
	}

	public void setMaestro(Maestro maestro) {
		this.maestro = maestro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoPerfil", nullable = false)
	public TipoPerfil getTipoPerfil() {
		return this.tipoPerfil;
	}

	public void setTipoPerfil(TipoPerfil tipoPerfil) {
		this.tipoPerfil = tipoPerfil;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "contrasena", nullable = false, length = 125)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(Set<Curso> cursos) {
		this.cursos = cursos;
	}

}
