package com.uanl.ss2020.model;
// default package
// Generated 26/06/2020 08:50:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", catalog = "sql9350583")
public class Grupo implements java.io.Serializable {

	private int idGrupo;
	private Materia materia;
	private int cantidadAlumnos;
	private Set<Curso> cursos = new HashSet<Curso>(0);

	public Grupo() {
	}

	public Grupo(int idGrupo, Materia materia, int cantidadAlumnos) {
		this.idGrupo = idGrupo;
		this.materia = materia;
		this.cantidadAlumnos = cantidadAlumnos;
	}

	public Grupo(int idGrupo, Materia materia, int cantidadAlumnos, Set<Curso> cursos) {
		this.idGrupo = idGrupo;
		this.materia = materia;
		this.cantidadAlumnos = cantidadAlumnos;
		this.cursos = cursos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idGrupo", unique = true, nullable = false)
	public int getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(int idGrupo) {
		this.idGrupo = idGrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMateria", nullable = false)
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Column(name = "cantidadAlumnos", nullable = false)
	public int getCantidadAlumnos() {
		return this.cantidadAlumnos;
	}

	public void setCantidadAlumnos(int cantidadAlumnos) {
		this.cantidadAlumnos = cantidadAlumnos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(Set<Curso> cursos) {
		this.cursos = cursos;
	}

}
