package com.uanl.ss2020.model;
// default package
// Generated 26/06/2020 08:50:58 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Maestro generated by hbm2java
 */
@Entity
@Table(name = "maestro", catalog = "sql9350583")
public class Maestro implements java.io.Serializable {

	private Integer idMaestro;
	private TipoMaestro tipoMaestro;
	private int numeroEmpleado;

	public Maestro() {
	}

	public Maestro(TipoMaestro tipoMaestro, int numeroEmpleado) {
		this.tipoMaestro = tipoMaestro;
		this.numeroEmpleado = numeroEmpleado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMaestro", unique = true, nullable = false)
	public Integer getIdMaestro() {
		return this.idMaestro;
	}

	public void setIdMaestro(Integer idMaestro) {
		this.idMaestro = idMaestro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoMaestro", nullable = false)
	public TipoMaestro getTipoMaestro() {
		return this.tipoMaestro;
	}

	public void setTipoMaestro(TipoMaestro tipoMaestro) {
		this.tipoMaestro = tipoMaestro;
	}

	@Column(name = "numeroEmpleado", nullable = false)
	public int getNumeroEmpleado() {
		return this.numeroEmpleado;
	}

	public void setNumeroEmpleado(int numeroEmpleado) {
		this.numeroEmpleado = numeroEmpleado;
	}

}
