package com.uanl.ss2020.model;
// default package
// Generated 26/06/2020 08:50:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMaestro generated by hbm2java
 */
@Entity
@Table(name = "tipoMaestro", catalog = "sql9350583")
public class TipoMaestro implements java.io.Serializable {

	private Integer idtipoMaestro;
	private String nombre;
	private Set<Maestro> maestros = new HashSet<Maestro>(0);

	public TipoMaestro() {
	}

	public TipoMaestro(String nombre) {
		this.nombre = nombre;
	}

	public TipoMaestro(String nombre, Set<Maestro> maestros) {
		this.nombre = nombre;
		this.maestros = maestros;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idtipoMaestro", unique = true, nullable = false)
	public Integer getIdtipoMaestro() {
		return this.idtipoMaestro;
	}

	public void setIdtipoMaestro(Integer idtipoMaestro) {
		this.idtipoMaestro = idtipoMaestro;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMaestro")
	public Set<Maestro> getMaestros() {
		return this.maestros;
	}

	public void setMaestros(Set<Maestro> maestros) {
		this.maestros = maestros;
	}

}
